# Generated by Django 4.1.7 on 2023-05-13 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_user_user_alter_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
