# Generated by Django 4.1.7 on 2023-05-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='Public', max_length=200),
        ),
    ]
